In [224]:
import os
import json
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv("/Users/madim/Desktop/ML_research/gender-classifier-DFE-791531.csv")
print len(df)

df = df[df.gender != 'brand']
df = df[df.gender != 'unknown']
df = df[df.gender.notnull()]

usernames = df['name']
users = []

for user in usernames:
    #print user
    users.append('@'+user)
    
print(users[0])
print(len(users))

20050
@sheezy0
12894

In [86]:
labels = df['gender']
print labels.nunique()

correct_labels_manset = []

# 1 is female, 0 is male
for label in labels:
    if label == "male":
        correct_labels_manset.append("__label__0 ")
    elif label == "female":
        correct_labels_manset.append("__label__1 ")
    else:
        print label
        
print len(correct_labels_manset)
print (type(correct_labels_manset))

2
12894
<type 'list'>

In [41]:
df.columns.values

array(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'gender', 'gender:confidence', 'profile_yn',
       'profile_yn:confidence', 'created', 'description', 'fav_number',
       'gender_gold', 'link_color', 'name', 'profile_yn_gold',
       'profileimage', 'retweet_count', 'sidebar_color', 'text',
       'tweet_coord', 'tweet_count', 'tweet_created', 'tweet_id',
       'tweet_location', 'user_timezone'], dtype=object)

In [89]:
manual_name = df['name']
manual_gender = df['gender']
manual_id = df['_unit_id']


manset = pd.concat([manual_name, manual_id, manual_gender], axis=1)

se = pd.Series(correct_labels_manset)

manset['labels'] = se.values

manset

                  name   _unit_id  gender       labels
0              sheezy0  815719226    male  __label__0
1          DavdBurnett  815719227    male  __label__0
2       lwtprettylaugh  815719228    male  __label__0
3          douggarland  815719229    male  __label__0
4         WilfordGemma  815719230  female  __label__1
5        monroevicious  815719231  female  __label__1
7           RobinMeske  815719233    male  __label__0
8            pigzilla_  815719234  female  __label__1
9        GabrieleNeher  815719235  female  __label__1
12      kaylanabrewer_  815719238  female  __label__1
14            cheyflan  815719240  female  __label__1
15           Ayu7sith4  815719241  female  __label__1
16        Toucaan_Samm  815719242  female  __label__1
17          SSmyth2010  815719243    male  __label__0
18     DarkToonsGaming  815719244    male  __label__0
20           jlpeter37  815719246  female  __label__1
21         SarahMaddry  815719247  female  __label__1
22            bethleia  815719248  female  __label__1
23         StrictlyAri  815719249    male  __label__0
24            JHurkett  815719250    male  __label__0
25       karenhbullard  815719251  female  __label__1
28     DearMoonshine__  815719254  female  __label__1
29            RinCutie  815719255    male  __label__0
31        HalRappaport  815719257    male  __label__0
32         sarahamiels  815719258  female  __label__1
33         TB12ForPrez  815719259    male  __label__0
35            300Stain  815719261    male  __label__0
37            __amira_  815719263  female  __label__1
39     brandonpattrson  815719265    male  __label__0
41         danydifazio  815719267    male  __label__0
...                ...        ...     ...          ...
20009       saidtaybae  815752702  female  __label__1
20010   philanthroupic  815752755  female  __label__1
20012        quise_tdb  815752898    male  __label__0
20013  donjohnsonpentz  815752948    male  __label__0
20014     DanOfCydonia  815753106    male  __label__0
20015         AvraCaro  815753655  female  __label__1
20016       sarahminda  815753740  female  __label__1
20018     marcscribner  815753864    male  __label__0
20019      aye_brenden  815754153    male  __label__0
20021    Montana_103rd  815754330    male  __label__0
20022     brianlkimich  815754362    male  __label__0
20023    5yellowdogdem  815754554    male  __label__0
20026        IanBealio  815755076    male  __label__0
20027      CeltsteveSr  815755206    male  __label__0
20028       ughcarolyn  815755336  female  __label__1
20031   tik_L_my_pik_L  815755604    male  __label__0
20032          FauxBen  815755689    male  __label__0
20033       norainacad  815755763  female  __label__1
20035   Cait89lovesTWD  815755887  female  __label__1
20036      sianfreyaxo  815756011  female  __label__1
20037      NickSherman  815756103    male  __label__0
20039  KaitlynAmendola  815756332  female  __label__1
20040     KenChronicle  815756417    male  __label__0
20043   MattChristmas1  815756700    male  __label__0
20044   Bigbootyyjudy_  815756767  female  __label__1
20045      capuletrosa  815757572  female  __label__1
20046       BenNight41  815757681    male  __label__0
20047    realuzzyfluxz  815757830    male  __label__0
20048     argumatronic  815757921  female  __label__1
20049      MeganFitz20  815757985  female  __label__1

[12894 rows x 4 columns]

In [53]:
# subset the manual set based on if they are active (which tweets we have crawled)

directory = '../manual_tweets/'

listofindices = []

for filename in os.listdir(directory):
    name = filename[1:-1]
    
    if name in manset['name']:
        print '*'

In [252]:
statefile = '../Re%3a_Sample_bias_/Manual_State.csv'

csv_data = pd.read_csv(statefile)
statedf = pd.DataFrame(csv_data)

countryfile = '../Re%3a_Sample_bias_/Manual_Country_data.csv'

csv_data2 = pd.read_csv(countryfile)
countrydf = pd.DataFrame(csv_data2)

countries = countrydf['country'].unique()
print countries
print 

states = statedf['state'].unique()
print states

["'United States'" "'Australia'" "'Argentina'" "'Peru'" "'Indonesia'"
 "'India'" "'Turkey'" "'Paraguay'" "'Japan'" "'Canada'" "'Mexico'"
 "'Brazil'" "'Thailand'" "'Ecuador'" "'Egypt'" "'South Africa'"
 "'Pakistan'" "'United Kingdom'" "'Spain'" "'Venezuela'" "'Philippines'"
 "'Colombia'" "'Chile'" "'Dominican Republic'" "'Costa Rica'" "'Germany'"
 "'Malaysia'" "'Honduras'" "'Italy'" "'Ireland'" "'Saudi Arabia'"
 "'Netherlands'" "'Portugal'" "'Bolivia'" "'Kuwait'" "'France'" "'Nigeria'"
 "'Bangladesh'" "'New Zealand'" "'Ghana'" "'Taiwan'" "'Qatar'" "'Greece'"
 "'Nicaragua'" "'Nepal'" "'Armenia'" "'Ivory Coast'" "'Denmark'"
 "'Hungary'" "'The Netherlands'"]

[" 'Pennsylvania'" " 'Victoria'" " 'Illinois'" " 'Florida'" " 'California'"
 " 'Alabama'" " 'Virginia'" " 'Utah'" " 'Nevada'" " 'New York'"
 " 'Colorado'" " 'Michigan'" " 'Arkansas'" " 'Indiana'" " 'Louisiana'"
 " 'Hawaii'" " 'Ontario'" " 'New Jersey'" " 'Maryland'" " 'Texas'"
 " 'Minnesota'" " 'Kentucky'" " 'Oregon'" " 'Delaware'" " 'Georgia'"
 " 'North Dakota'" " 'North Carolina'" " 'Washington'" " 'Tennessee'"
 " 'Massachusetts'" " 'Ohio'" " 'Wisconsin'" " 'Connecticut'" " 'Iowa'"
 " 'Missouri'" " 'San Jose'" " 'Arizona'" " 'South Carolina'"
 " 'District of Columbia'" " 'Mississippi'" " 'Maine'" " 'Alaska'"
 " 'West Virginia'" " 'Vermont'" " 'Rhode Island'" " 'Kansas'" " 'Montana'"
 " 'Nebraska'" " 'Idaho'" " 'Wyoming'" " 'South Dakota'"]

In [3]:
labels = df['gender']
print labels.nunique()

correct_labels = []

# 1 is female, 0 is male
for label in labels:
    if label == "male":
        correct_labels.append("__label__0 ")
    elif label == "female":
        correct_labels.append("__label__1 ")
    else:
        print label

2

In [4]:
print len(users)
print len(correct_labels)

12894
12894

In [12]:
%%time

directory = '../manual_tweets/'

inactive = 0
totalusers = 0
users = 0

filenames = []

for filename in os.listdir(directory):
    filename = directory+filename
    totalusers += 1
    
    filenames.append(filename)
    
print(totalusers, " number of total users")
print len(filenames)

(12310, ' number of total users')
12310
Wall time: 66 ms

In [83]:
filenames

2
12894

In [80]:
manset['name']

row = manset.loc[manset['name'] == '0154_GUTIERREZ']
print row

                name   _unit_id  gender
7632  0154_GUTIERREZ  815726952  female

In [211]:
%%time

numactive = 0
len_eachtimeline = []

for filename in filenames:
    screenname = filename[18:-4]
    row = manset.loc[manset['name'] == screenname]
    #print row
    
    with open(filename, "r") as tweets_file:
        timeline = []
        tweet = []
        for line in tweets_file:
            append = False
            for word in line.split():            
                if word == '"text":':
                    append = True

                if append == True and word != '"is_quote_status":':
                    tweet.append(word)

                if '"is_quote_status":' in word:
                    del tweet[0]
                    timeline.append(tweet)
                    tweet = []
                    append = False     
    
    # doesnt catch all of the values on the first run for some reason
    # takes a couple of loops of processign to get what we want
    l = 100 
    while l != 0:
        l = clean(timeline)
    
    if len(timeline) > 0:
        len_eachtimeline.append(len(timeline))
    
        # write to file
        #l = row['labels'].values
        #write_timeline(timeline, screenname, l[0])
    
    
    if len(timeline) > 0:
        numactive += 1
        
        
print numactive

755
Wall time: 4min 6s

In [220]:
print len(len_eachtimeline)

index = 0
i = 0
for x in len_eachtimeline:
    if x < 200:
        i += 1
        del len_eachtimeline[index]
    index += 1

    
print len(len_eachtimeline)

699
699

In [221]:
print "Average number of tweets per users: ", reduce(lambda x, y: x + y, len_eachtimeline) / len(len_eachtimeline)

num = 0
for x in len_eachtimeline:
    if x > 200:
        num = x/200 + num
        
print "updated number of instances now: ", num

Average number of tweets per users:  3186
updated number of instances now:  10801

In [225]:
np.sum(len_eachtimeline)

2227076

In [123]:
def clean(timelines):
    i = 0
    l = 0
    for t in timelines:
        if '"urls":' in t or '"media":' in t or '[{"url":' in t or "RT" in t:
            del timelines[i]
            l += 1
        i += 1
        
    return l

In [125]:

def write_timeline(timeline, filename, label):
    fname = '../extended_manual/'+filename+'_extended.txt'
    
    with open(fname, 'a+') as f:
        f.write(label)
        
        numtweets = 0
        for tweet in timeline:
            for word in tweet:
                #print word
                f.write(word)
                f.write(' ')
            numtweets += 1
            if numtweets == 200:
                f.write('\n')
                f.write(label)
                numtweets = 0
                
            f.write('\t')

In [145]:
def create_list_offilestowrite(file):
    filenames = []
    csv_data = pd.read_csv(file,low_memory = False)
    df = pd.DataFrame(csv_data)
    group1 = df.groupby(['country']).count()
    countries = df['country'].unique()
    
    for country in countries:
        country = country.strip('\'')
        #print(country)
        filename = '../locations_manual/countries/manual_country_'+country+'.txt'
        filenames.append(filename)

    return filenames
    #print(filenames)

In [173]:
def create_list_offilestowrite_states(file):
    filenames = []

    csv_data = pd.read_csv(file,low_memory = False)
    df = pd.DataFrame(csv_data)
    #group1 = df.groupby(['state']).count()
    states = df['state'].unique()
    
    for state in states:
        state = state.strip('\'')
        state = state.strip('\'')
        #print(country)
        filename = '../locations_manual/states/manual_state_'+state+'.txt'
        filename = filename.replace("'", "")
        filename = filename.replace(" ", "")
        
        filenames.append(filename)

    return filenames
    #print(filenames)

In [193]:
def subset_ids_bycountry(file):
    ids_bycountry = []

    csv_data = pd.read_csv(file,low_memory = False)
    df = pd.DataFrame(csv_data)
    group1 = df.groupby(['country']).count()
    countries = df['country'].unique()
    
    countryids = []
    for country in countries:
        ids = []
        countrydf = df[df['country'] == country]
        print(countrydf)
        
        ids = countrydf['id']
        countryids.append(ids)

    return countryids

In [141]:
def subset_ids_bystate(file):

    csv_data = pd.read_csv(file,low_memory = False)
    df = pd.DataFrame(csv_data)
    states = df['state'].unique()
    
    stateids = []
    for state in states:
        ids = []
        statedf = df[df['state'] == state]
        #print(countrydf)
        
        ids = statedf['id']
        stateids.append(ids)

    return stateids

In [194]:
statefile = '../Re%3a_Sample_bias_/Manual_State.csv'

csv_data = pd.read_csv(statefile)
statedf = pd.DataFrame(csv_data)

countryfile = '../Re%3a_Sample_bias_/Manual_Country_data.csv'

csv_data2 = pd.read_csv(countryfile)
countrydf = pd.DataFrame(csv_data2)


#### For countries
country_filenames = create_list_offilestowrite(countryfile)
countryids = subset_ids_bycountry(countryfile)
which = "COUNTRY"

##### For states
state_filenames = create_list_offilestowrite_states(statefile)
stateids = subset_ids_bystate(statefile)
which = "STATE"

print len(countryids)

             id          country
0     815720500  'United States'
1     815720515  'United States'
3     815720519  'United States'
10    815720536  'United States'
11    815720542  'United States'
12    815720543  'United States'
14    815720558  'United States'
15    815720570  'United States'
16    815720571  'United States'
19    815720581  'United States'
21    815720586  'United States'
22    815720587  'United States'
25    815720601  'United States'
26    815720602  'United States'
28    815720612  'United States'
29    815720614  'United States'
30    815720615  'United States'
32    815720618  'United States'
33    815720623  'United States'
34    815720626  'United States'
35    815720627  'United States'
36    815720628  'United States'
39    815720660  'United States'
40    815720661  'United States'
43    815720670  'United States'
46    815720689  'United States'
47    815720692  'United States'
48    815720697  'United States'
49    815720698  'United States'
50    815720700  'United States'
...         ...              ...
2437  815721884  'United States'
2438  815721885  'United States'
2440  815721890  'United States'
2443  815721900  'United States'
2448  815721915  'United States'
2449  815721868  'United States'
2452  815721873  'United States'
2454  815721883  'United States'
2455  815721884  'United States'
2456  815721885  'United States'
2458  815721890  'United States'
2461  815721900  'United States'
2462  815721915  'United States'
2465  815721930  'United States'
2466  815721935  'United States'
2468  815721942  'United States'
2469  815721946  'United States'
2470  815721951  'United States'
2471  815721955  'United States'
2472  815721958  'United States'
2473  815721959  'United States'
2475  815722032  'United States'
2476  815721987  'United States'
2480  815722095  'United States'
2487  815722116  'United States'
2489  815722123  'United States'
2491  815722142  'United States'
2494  815722149  'United States'
2496  815722154  'United States'
2498  815722177  'United States'

[1375 rows x 2 columns]
             id      country
2     815720517  'Australia'
144   815721033  'Australia'
182   815721157  'Australia'
193   815721180  'Australia'
209   815721244  'Australia'
257   815721419  'Australia'
289   815721533  'Australia'
345   815721727  'Australia'
436   815722082  'Australia'
479   815722216  'Australia'
491   815722271  'Australia'
510   815722332  'Australia'
514   815722348  'Australia'
521   815722376  'Australia'
539   815722416  'Australia'
541   815722425  'Australia'
553   815722461  'Australia'
592   815722600  'Australia'
640   815722761  'Australia'
654   815722851  'Australia'
713   815723034  'Australia'
739   815723124  'Australia'
748   815723170  'Australia'
773   815723252  'Australia'
775   815723255  'Australia'
852   815723541  'Australia'
896   815723713  'Australia'
1028  815724163  'Australia'
1047  815724223  'Australia'
1060  815724276  'Australia'
...         ...          ...
1632  815726328  'Australia'
1661  815726438  'Australia'
1673  815726472  'Australia'
1679  815726489  'Australia'
1728  815726644  'Australia'
1749  815726695  'Australia'
1800  815726863  'Australia'
1847  815727048  'Australia'
1874  815727167  'Australia'
1878  815727189  'Australia'
1903  815727274  'Australia'
1926  815727344  'Australia'
1938  815727397  'Australia'
1945  815727430  'Australia'
1954  815727456  'Australia'
1980  815727582  'Australia'
2033  815727775  'Australia'
2049  815727827  'Australia'
2052  815727844  'Australia'
2055  815727855  'Australia'
2208  815728477  'Australia'
2308  815728888  'Australia'
2312  815728895  'Australia'
2341  815728991  'Australia'
2362  815729097  'Australia'
2366  815729105  'Australia'
2395  815729195  'Australia'
2439  815721887  'Australia'
2447  815721908  'Australia'
2457  815721887  'Australia'

[75 rows x 2 columns]
             id      country
4     815720520  'Argentina'
7     815720530  'Argentina'
76    815720771  'Argentina'
99    815720834  'Argentina'
108   815720869  'Argentina'
115   815720886  'Argentina'
140   815721005  'Argentina'
150   815721060  'Argentina'
181   815721156  'Argentina'
183   815721159  'Argentina'
199   815721191  'Argentina'
201   815721211  'Argentina'
215   815721274  'Argentina'
252   815721410  'Argentina'
320   815721636  'Argentina'
331   815721682  'Argentina'
334   815721698  'Argentina'
339   815721705  'Argentina'
340   815721709  'Argentina'
341   815721718  'Argentina'
355   815721774  'Argentina'
382   815721872  'Argentina'
416   815722000  'Argentina'
442   815722111  'Argentina'
446   815722118  'Argentina'
482   815722234  'Argentina'
492   815722276  'Argentina'
501   815722294  'Argentina'
502   815722298  'Argentina'
536   815722408  'Argentina'
...         ...          ...
1851  815727078  'Argentina'
1857  815727113  'Argentina'
1870  815727155  'Argentina'
1879  815727190  'Argentina'
1923  815727329  'Argentina'
1959  815727490  'Argentina'
1962  815727500  'Argentina'
1967  815727511  'Argentina'
1977  815727573  'Argentina'
1981  815727585  'Argentina'
1983  815727600  'Argentina'
2013  815727705  'Argentina'
2027  815727759  'Argentina'
2040  815727802  'Argentina'
2042  815727805  'Argentina'
2114  815728070  'Argentina'
2127  815728107  'Argentina'
2128  815728110  'Argentina'
2159  815728253  'Argentina'
2160  815728260  'Argentina'
2192  815728396  'Argentina'
2205  815728452  'Argentina'
2279  815728781  'Argentina'
2286  815728800  'Argentina'
2292  815728819  'Argentina'
2348  815729034  'Argentina'
2349  815729035  'Argentina'
2355  815729069  'Argentina'
2368  815729112  'Argentina'
2390  815729170  'Argentina'

[116 rows x 2 columns]
             id country
5     815720521  'Peru'
23    815720589  'Peru'
325   815721649  'Peru'
376   815721853  'Peru'
437   815722085  'Peru'
476   815722209  'Peru'
558   815722486  'Peru'
737   815723119  'Peru'
745   815723152  'Peru'
874   815723625  'Peru'
1020  815724129  'Peru'
1421  815725621  'Peru'
1739  815726666  'Peru'
1817  815726927  'Peru'
1818  815726928  'Peru'
1820  815726931  'Peru'
1883  815727198  'Peru'
1976  815727561  'Peru'
2022  815727736  'Peru'
2028  815727763  'Peru'
2092  815727984  'Peru'
2198  815728432  'Peru'
2199  815728436  'Peru'
2209  815728478  'Peru'
2301  815728865  'Peru'
2317  815728907  'Peru'
2330  815728953  'Peru'
2380  815729140  'Peru'
2403  815721690  'Peru'
2411  815721794  'Peru'
2426  815721794  'Peru'
             id      country
6     815720525  'Indonesia'
8     815720532  'Indonesia'
120   815720901  'Indonesia'
133   815720929  'Indonesia'
161   815721099  'Indonesia'
173   815721124  'Indonesia'
177   815721135  'Indonesia'
222   815721302  'Indonesia'
226   815721331  'Indonesia'
248   815721401  'Indonesia'
262   815721426  'Indonesia'
392   815721917  'Indonesia'
657   815722857  'Indonesia'
784   815723283  'Indonesia'
789   815723302  'Indonesia'
899   815723716  'Indonesia'
904   815723734  'Indonesia'
917   815723771  'Indonesia'
940   815723842  'Indonesia'
949   815723876  'Indonesia'
969   815723953  'Indonesia'
975   815723980  'Indonesia'
986   815724011  'Indonesia'
994   815724040  'Indonesia'
1045  815724219  'Indonesia'
1049  815724239  'Indonesia'
1053  815724254  'Indonesia'
1083  815724348  'Indonesia'
1092  815724377  'Indonesia'
1103  815724407  'Indonesia'
...         ...          ...
1479  815725863  'Indonesia'
1509  815725955  'Indonesia'
1601  815726227  'Indonesia'
1666  815726462  'Indonesia'
1693  815726520  'Indonesia'
1696  815726529  'Indonesia'
1750  815726696  'Indonesia'
1765  815726748  'Indonesia'
1821  815726932  'Indonesia'
1867  815727141  'Indonesia'
1887  815727211  'Indonesia'
1990  815727636  'Indonesia'
2009  815727697  'Indonesia'
2016  815727711  'Indonesia'
2032  815727774  'Indonesia'
2034  815727778  'Indonesia'
2054  815727852  'Indonesia'
2059  815727872  'Indonesia'
2076  815727938  'Indonesia'
2079  815727949  'Indonesia'
2088  815727967  'Indonesia'
2089  815727968  'Indonesia'
2108  815728050  'Indonesia'
2110  815728057  'Indonesia'
2131  815728116  'Indonesia'
2145  815728171  'Indonesia'
2244  815728625  'Indonesia'
2256  815728670  'Indonesia'
2337  815728982  'Indonesia'
2343  815729000  'Indonesia'

[71 rows x 2 columns]
             id  country
9     815720534  'India'
62    815720739  'India'
137   815721000  'India'
167   815721111  'India'
207   815721242  'India'
299   815721576  'India'
344   815721726  'India'
375   815721851  'India'
403   815721949  'India'
414   815721988  'India'
518   815722357  'India'
524   815722384  'India'
552   815722455  'India'
559   815722487  'India'
568   815722503  'India'
578   815722537  'India'
581   815722546  'India'
597   815722620  'India'
601   815722635  'India'
741   815723137  'India'
746   815723160  'India'
765   815723228  'India'
793   815723319  'India'
803   815723349  'India'
855   815723545  'India'
866   815723584  'India'
928   815723813  'India'
964   815723929  'India'
1002  815724068  'India'
1041  815724206  'India'
...         ...      ...
1685  815726503  'India'
1698  815726534  'India'
1708  815726575  'India'
1727  815726641  'India'
1747  815726690  'India'
1754  815726711  'India'
1783  815726823  'India'
1806  815726888  'India'
1810  815726902  'India'
1832  815726977  'India'
1843  815727032  'India'
1875  815727172  'India'
1931  815727375  'India'
2006  815727693  'India'
2026  815727756  'India'
2030  815727767  'India'
2066  815727898  'India'
2123  815728088  'India'
2134  815728121  'India'
2161  815728261  'India'
2197  815728429  'India'
2216  815728511  'India'
2235  815728601  'India'
2259  815728692  'India'
2270  815728739  'India'
2273  815728759  'India'
2324  815728933  'India'
2325  815728938  'India'
2338  815728987  'India'
2344  815729002  'India'

[92 rows x 2 columns]
             id   country
13    815720554  'Turkey'
41    815720662  'Turkey'
204   815721231  'Turkey'
1581  815726179  'Turkey'
1611  815726255  'Turkey'
             id     country
17    815720574  'Paraguay'
162   815721100  'Paraguay'
557   815722485  'Paraguay'
1204  815724772  'Paraguay'
1406  815725563  'Paraguay'
1450  815725743  'Paraguay'
1714  815726592  'Paraguay'
1949  815727442  'Paraguay'
2056  815727861  'Paraguay'
             id  country
18    815720580  'Japan'
59    815720724  'Japan'
83    815720785  'Japan'
151   815721063  'Japan'
368   815721813  'Japan'
450   815722128  'Japan'
575   815722526  'Japan'
753   815723184  'Japan'
817   815723392  'Japan'
845   815723508  'Japan'
860   815723568  'Japan'
1075  815724333  'Japan'
1118  815724468  'Japan'
1122  815724492  'Japan'
1266  815725024  'Japan'
1391  815725526  'Japan'
1419  815725615  'Japan'
1512  815725964  'Japan'
1636  815726344  'Japan'
1671  815726467  'Japan'
1682  815726494  'Japan'
1686  815726504  'Japan'
1732  815726654  'Japan'
1766  815726751  'Japan'
1802  815726867  'Japan'
1890  815727224  'Japan'
1912  815727295  'Japan'
1979  815727579  'Japan'
1991  815727637  'Japan'
2144  815728168  'Japan'
2181  815728361  'Japan'
2202  815728447  'Japan'
2299  815728853  'Japan'
2409  815721786  'Japan'
2415  815721806  'Japan'
2424  815721786  'Japan'
2429  815721863  'Japan'
2433  815721872  'Japan'
2446  815721907  'Japan'
2451  815721872  'Japan'
2477  815722000  'Japan'
2484  815722108  'Japan'
             id   country
20    815720584  'Canada'
44    815720671  'Canada'
45    815720685  'Canada'
55    815720712  'Canada'
82    815720784  'Canada'
91    815720808  'Canada'
107   815720858  'Canada'
109   815720875  'Canada'
141   815721006  'Canada'
168   815721112  'Canada'
200   815721192  'Canada'
205   815721232  'Canada'
223   815721305  'Canada'
237   815721371  'Canada'
258   815721420  'Canada'
324   815721648  'Canada'
421   815722032  'Canada'
459   815722168  'Canada'
461   815722175  'Canada'
465   815722185  'Canada'
504   815722302  'Canada'
540   815722419  'Canada'
560   815722489  'Canada'
573   815722520  'Canada'
606   815722650  'Canada'
621   815722701  'Canada'
636   815722748  'Canada'
710   815723016  'Canada'
729   815723106  'Canada'
777   815723257  'Canada'
...         ...       ...
1723  815726630  'Canada'
1794  815726850  'Canada'
1848  815727051  'Canada'
1860  815727122  'Canada'
1861  815727124  'Canada'
1863  815727131  'Canada'
1864  815727133  'Canada'
1922  815727325  'Canada'
1961  815727496  'Canada'
2043  815727807  'Canada'
2044  815727809  'Canada'
2062  815727882  'Canada'
2070  815727908  'Canada'
2101  815728002  'Canada'
2104  815728019  'Canada'
2124  815728095  'Canada'
2136  815728129  'Canada'
2154  815728201  'Canada'
2179  815728354  'Canada'
2188  815728381  'Canada'
2200  815728437  'Canada'
2201  815728443  'Canada'
2257  815728686  'Canada'
2314  815728900  'Canada'
2315  815728903  'Canada'
2367  815729107  'Canada'
2394  815729184  'Canada'
2401  815721676  'Canada'
2464  815721928  'Canada'
2474  815721961  'Canada'

[98 rows x 2 columns]
             id   country
24    815720593  'Mexico'
380   815721865  'Mexico'
556   815722477  'Mexico'
677   815722906  'Mexico'
734   815723116  'Mexico'
778   815723263  'Mexico'
832   815723465  'Mexico'
846   815723524  'Mexico'
885   815723661  'Mexico'
973   815723971  'Mexico'
1036  815724183  'Mexico'
1124  815724497  'Mexico'
1315  815725249  'Mexico'
1362  815725454  'Mexico'
1608  815726251  'Mexico'
2386  815729160  'Mexico'
             id   country
27    815720609  'Brazil'
38    815720657  'Brazil'
42    815720665  'Brazil'
75    815720770  'Brazil'
89    815720804  'Brazil'
93    815720818  'Brazil'
98    815720832  'Brazil'
100   815720835  'Brazil'
110   815720876  'Brazil'
123   815720907  'Brazil'
149   815721052  'Brazil'
153   815721066  'Brazil'
154   815721068  'Brazil'
189   815721166  'Brazil'
208   815721243  'Brazil'
216   815721277  'Brazil'
219   815721294  'Brazil'
260   815721422  'Brazil'
268   815721456  'Brazil'
274   815721484  'Brazil'
276   815721490  'Brazil'
280   815721505  'Brazil'
283   815721516  'Brazil'
290   815721534  'Brazil'
300   815721580  'Brazil'
304   815721589  'Brazil'
363   815721800  'Brazil'
417   815722001  'Brazil'
434   815722077  'Brazil'
451   815722131  'Brazil'
...         ...       ...
2073  815727912  'Brazil'
2090  815727980  'Brazil'
2106  815728027  'Brazil'
2116  815728074  'Brazil'
2133  815728119  'Brazil'
2214  815728499  'Brazil'
2215  815728509  'Brazil'
2217  815728521  'Brazil'
2224  815728543  'Brazil'
2229  815728565  'Brazil'
2230  815728571  'Brazil'
2231  815728577  'Brazil'
2241  815728622  'Brazil'
2243  815728624  'Brazil'
2262  815728697  'Brazil'
2288  815728811  'Brazil'
2309  815728890  'Brazil'
2318  815728914  'Brazil'
2351  815729041  'Brazil'
2360  815729077  'Brazil'
2365  815729104  'Brazil'
2369  815729114  'Brazil'
2378  815729137  'Brazil'
2382  815729143  'Brazil'
2385  815729154  'Brazil'
2406  815721763  'Brazil'
2428  815721862  'Brazil'
2478  815722075  'Brazil'
2483  815722102  'Brazil'
2493  815722146  'Brazil'

[151 rows x 2 columns]
             id     country
31    815720617  'Thailand'
77    815720774  'Thailand'
85    815720792  'Thailand'
190   815721167  'Thailand'
234   815721365  'Thailand'
308   815721599  'Thailand'
806   815723352  'Thailand'
909   815723747  'Thailand'
921   815723787  'Thailand'
941   815723849  'Thailand'
1054  815724261  'Thailand'
1072  815724329  'Thailand'
1104  815724413  'Thailand'
1235  815724904  'Thailand'
1252  815724982  'Thailand'
1286  815725112  'Thailand'
1415  815725594  'Thailand'
1437  815725707  'Thailand'
1491  815725894  'Thailand'
1498  815725924  'Thailand'
1504  815725939  'Thailand'
1599  815726217  'Thailand'
1694  815726524  'Thailand'
1871  815727156  'Thailand'
1889  815727220  'Thailand'
1937  815727393  'Thailand'
2285  815728795  'Thailand'
2340  815728989  'Thailand'
2463  815721927  'Thailand'
             id    country
37    815720649  'Ecuador'
106   815720857  'Ecuador'
305   815721593  'Ecuador'
407   815721964  'Ecuador'
439   815722096  'Ecuador'
624   815722708  'Ecuador'
660   815722861  'Ecuador'
681   815722915  'Ecuador'
736   815723118  'Ecuador'
971   815723963  'Ecuador'
1187  815724717  'Ecuador'
1449  815725741  'Ecuador'
1701  815726544  'Ecuador'
1798  815726857  'Ecuador'
1799  815726860  'Ecuador'
2147  815728178  'Ecuador'
2168  815728290  'Ecuador'
2381  815729141  'Ecuador'
             id  country
51    815720703  'Egypt'
227   815721336  'Egypt'
864   815723579  'Egypt'
1016  815724116  'Egypt'
1148  815724608  'Egypt'
1503  815725937  'Egypt'
1642  815726360  'Egypt'
1805  815726883  'Egypt'
2242  815728623  'Egypt'
             id         country
52    815720707  'South Africa'
1729  815726647  'South Africa'
1745  815726688  'South Africa'
1846  815727045  'South Africa'
1973  815727538  'South Africa'
2213  815728496  'South Africa'
2281  815728787  'South Africa'
2307  815728887  'South Africa'
2335  815728976  'South Africa'
2488  815722119  'South Africa'
2495  815722150  'South Africa'
             id     country
64    815720741  'Pakistan'
265   815721436  'Pakistan'
315   815721622  'Pakistan'
585   815722553  'Pakistan'
1417  815725607  'Pakistan'
1869  815727148  'Pakistan'
1888  815727218  'Pakistan'
2100  815728001  'Pakistan'
             id           country
71    815720763  'United Kingdom'
271   815721469  'United Kingdom'
426   815722056  'United Kingdom'
456   815722144  'United Kingdom'
468   815722191  'United Kingdom'
488   815722250  'United Kingdom'
551   815722450  'United Kingdom'
571   815722515  'United Kingdom'
595   815722613  'United Kingdom'
596   815722614  'United Kingdom'
611   815722663  'United Kingdom'
616   815722685  'United Kingdom'
618   815722691  'United Kingdom'
637   815722751  'United Kingdom'
641   815722765  'United Kingdom'
647   815722798  'United Kingdom'
661   815722866  'United Kingdom'
707   815723005  'United Kingdom'
721   815723074  'United Kingdom'
733   815723115  'United Kingdom'
735   815723117  'United Kingdom'
740   815723132  'United Kingdom'
763   815723224  'United Kingdom'
772   815723247  'United Kingdom'
791   815723316  'United Kingdom'
837   815723482  'United Kingdom'
844   815723507  'United Kingdom'
865   815723582  'United Kingdom'
882   815723649  'United Kingdom'
922   815723791  'United Kingdom'
...         ...               ...
1710  815726581  'United Kingdom'
1730  815726650  'United Kingdom'
1753  815726705  'United Kingdom'
1755  815726712  'United Kingdom'
1775  815726781  'United Kingdom'
1812  815726906  'United Kingdom'
1830  815726965  'United Kingdom'
1858  815727114  'United Kingdom'
1885  815727205  'United Kingdom'
1906  815727284  'United Kingdom'
1919  815727310  'United Kingdom'
1921  815727312  'United Kingdom'
2008  815727696  'United Kingdom'
2023  815727745  'United Kingdom'
2068  815727901  'United Kingdom'
2105  815728020  'United Kingdom'
2148  815728179  'United Kingdom'
2219  815728528  'United Kingdom'
2266  815728724  'United Kingdom'
2294  815728830  'United Kingdom'
2364  815729102  'United Kingdom'
2402  815721685  'United Kingdom'
2435  815721876  'United Kingdom'
2444  815721903  'United Kingdom'
2453  815721876  'United Kingdom'
2467  815721937  'United Kingdom'
2479  815722094  'United Kingdom'
2485  815722110  'United Kingdom'
2492  815722145  'United Kingdom'
2497  815722110  'United Kingdom'

[76 rows x 2 columns]
             id  country
78    815720775  'Spain'
138   815721001  'Spain'
343   815721723  'Spain'
361   815721795  'Spain'
405   815721961  'Spain'
471   815722197  'Spain'
550   815722445  'Spain'
800   815723338  'Spain'
1261  815725008  'Spain'
1565  815726137  'Spain'
2486  815722111  'Spain'
             id      country
79    815720779  'Venezuela'
90    815720806  'Venezuela'
102   815720850  'Venezuela'
139   815721002  'Venezuela'
282   815721512  'Venezuela'
358   815721785  'Venezuela'

             id  country
184   815721160  'Italy'
415   815721994  'Italy'
631   815722727  'Italy'
808   815723357  'Italy'
869   815723592  'Italy'
1347  815725400  'Italy'
1368  815725475  'Italy'
1542  815726042  'Italy'
2095  815727987  'Italy'
             id    country
187   815721164  'Ireland'
698   815722967  'Ireland'
1476  815725856  'Ireland'
1678  815726485  'Ireland'
             id         country
241   815721379  'Saudi Arabia'
458   815722167  'Saudi Arabia'
1855  815727100  'Saudi Arabia'
2249  815728641  'Saudi Arabia'
             id        country
256   815721418  'Netherlands'
372   815721844  'Netherlands'
396   815721924  'Netherlands'
664   815722875  'Netherlands'
826   815723427  'Netherlands'
915   815723761  'Netherlands'
1346  815725397  'Netherlands'
2404  815721691  'Netherlands'
2482  815722099  'Netherlands'
             id     country
327   815721677  'Portugal'
481   815722227  'Portugal'
1288  815725115  'Portugal'
2048  815727821  'Portugal'
             id    country
357   815721783  'Bolivia'
1996  815727655  'Bolivia'
             id   country
425   815722049  'Kuwait'
2245  815728627  'Kuwait'
             id   country
433   815722075  'France'
483   815722235  'France'
732   815723114  'France'
810   815723359  'France'
816   815723386  'France'
906   815723742  'France'
1026  815724150  'France'
1260  815725007  'France'
1279  815725082  'France'
1320  815725288  'France'
1386  815725512  'France'
1550  815726071  'France'
1586  815726189  'France'
1597  815726213  'France'
1624  815726308  'France'
1757  815726717  'France'
1780  815726809  'France'
1911  815727292  'France'
2015  815727707  'France'
2035  815727779  'France'
2051  815727843  'France'
2075  815727928  'France'
2189  815728383  'France'
2321  815728923  'France'
2373  815729124  'France'
             id    country
569   815722506  'Nigeria'
599   815722631  'Nigeria'
853   815723543  'Nigeria'
857   815723552  'Nigeria'
1207  815724781  'Nigeria'
1303  815725195  'Nigeria'
1373  815725490  'Nigeria'
1925  815727337  'Nigeria'
1936  815727390  'Nigeria'
2153  815728196  'Nigeria'
             id       country
607   815722651  'Bangladesh'
1868  815727144  'Bangladesh'
             id        country
646   815722793  'New Zealand'
893   815723698  'New Zealand'
974   815723973  'New Zealand'
1510  815725958  'New Zealand'
1621  815726297  'New Zealand'
2082  815727956  'New Zealand'
             id  country
655   815722854  'Ghana'
1410  815725582  'Ghana'
1674  815726474  'Ghana'
1993  815727651  'Ghana'
2126  815728105  'Ghana'
             id   country
774   815723254  'Taiwan'
2087  815727965  'Taiwan'
2418  815721821  'Taiwan'
            id  country
879  815723640  'Qatar'
             id   country
880   815723646  'Greece'
1521  815725984  'Greece'
1823  815726941  'Greece'
             id      country
1203  815724763  'Nicaragua'
1442  815725721  'Nicaragua'
             id  country
1458  815725784  'Nepal'
             id    country
1505  815725948  'Armenia'
             id        country
1787  815726828  'Ivory Coast'
             id    country
2097  815727993  'Denmark'
             id    country
2432  815721871  'Hungary'
2450  815721871  'Hungary'
             id            country
2442  815721899  'The Netherlands'
2460  815721899  'The Netherlands'
2481  815722098  'The Netherlands'
2490  815722132  'The Netherlands'
50

In [195]:
#manset
#countryids
country_filenames

['../locations_manual/countries/manual_country_United States.txt',
 '../locations_manual/countries/manual_country_Australia.txt',
 '../locations_manual/countries/manual_country_Argentina.txt',
 '../locations_manual/countries/manual_country_Peru.txt',
 '../locations_manual/countries/manual_country_Indonesia.txt',
 '../locations_manual/countries/manual_country_India.txt',
 '../locations_manual/countries/manual_country_Turkey.txt',
 '../locations_manual/countries/manual_country_Paraguay.txt',
 '../locations_manual/countries/manual_country_Japan.txt',
 '../locations_manual/countries/manual_country_Canada.txt',
 '../locations_manual/countries/manual_country_Mexico.txt',
 '../locations_manual/countries/manual_country_Brazil.txt',
 '../locations_manual/countries/manual_country_Thailand.txt',
 '../locations_manual/countries/manual_country_Ecuador.txt',
 '../locations_manual/countries/manual_country_Egypt.txt',
 '../locations_manual/countries/manual_country_South Africa.txt',
 '../locations_manual/countries/manual_country_Pakistan.txt',
 '../locations_manual/countries/manual_country_United Kingdom.txt',
 '../locations_manual/countries/manual_country_Spain.txt',
 '../locations_manual/countries/manual_country_Venezuela.txt',
 '../locations_manual/countries/manual_country_Philippines.txt',
 '../locations_manual/countries/manual_country_Colombia.txt',
 '../locations_manual/countries/manual_country_Chile.txt',
 '../locations_manual/countries/manual_country_Dominican Republic.txt',
 '../locations_manual/countries/manual_country_Costa Rica.txt',
 '../locations_manual/countries/manual_country_Germany.txt',
 '../locations_manual/countries/manual_country_Malaysia.txt',
 '../locations_manual/countries/manual_country_Honduras.txt',
 '../locations_manual/countries/manual_country_Italy.txt',
 '../locations_manual/countries/manual_country_Ireland.txt',
 '../locations_manual/countries/manual_country_Saudi Arabia.txt',
 '../locations_manual/countries/manual_country_Netherlands.txt',
 '../locations_manual/countries/manual_country_Portugal.txt',
 '../locations_manual/countries/manual_country_Bolivia.txt',
 '../locations_manual/countries/manual_country_Kuwait.txt',
 '../locations_manual/countries/manual_country_France.txt',
 '../locations_manual/countries/manual_country_Nigeria.txt',
 '../locations_manual/countries/manual_country_Bangladesh.txt',
 '../locations_manual/countries/manual_country_New Zealand.txt',
 '../locations_manual/countries/manual_country_Ghana.txt',
 '../locations_manual/countries/manual_country_Taiwan.txt',
 '../locations_manual/countries/manual_country_Qatar.txt',
 '../locations_manual/countries/manual_country_Greece.txt',
 '../locations_manual/countries/manual_country_Nicaragua.txt',
 '../locations_manual/countries/manual_country_Nepal.txt',
 '../locations_manual/countries/manual_country_Armenia.txt',
 '../locations_manual/countries/manual_country_Ivory Coast.txt',
 '../locations_manual/countries/manual_country_Denmark.txt',
 '../locations_manual/countries/manual_country_Hungary.txt',
 '../locations_manual/countries/manual_country_The Netherlands.txt']

In [207]:
%%time

# create country subsets
#for cname in country_filenames:

numactive = 0
len_eachtimeline = []

for filename in filenames:
    screenname = filename[18:-4]
    row = manset.loc[manset['name'] == screenname]
    
    with open(filename, "r") as tweets_file:
        timeline = []
        tweet = []
        for line in tweets_file:
            append = False
            for word in line.split():            
                if word == '"text":':
                    append = True

                if append == True and word != '"is_quote_status":':
                    tweet.append(word)

                if '"is_quote_status":' in word:
                    del tweet[0]
                    timeline.append(tweet)
                    tweet = []
                    append = False    
                    
    # doesnt catch all of the values on the first run for some reason
    # takes a couple of loops of processign to get what we want
    l = 100 
    while l != 0:
        l = clean(timeline)

    
    id = row['_unit_id'].values[0]
    #print id

    cindex = 0
    if len(timeline) > 0:
        for country in countryids:
            if id in country.values:
                # write to file
                l_ = row['labels'].values[0]
                fname = country_filenames[cindex]
                write_timeline_country(timeline, fname, l_)

            cindex += 1

Wall time: 5min 5s

In [208]:
%%time

# create country subsets
#for cname in country_filenames:

numactive = 0
len_eachtimeline = []

for filename in filenames:
    screenname = filename[18:-4]
    row = manset.loc[manset['name'] == screenname]
    
    with open(filename, "r") as tweets_file:
        timeline = []
        tweet = []
        for line in tweets_file:
            append = False
            for word in line.split():            
                if word == '"text":':
                    append = True

                if append == True and word != '"is_quote_status":':
                    tweet.append(word)

                if '"is_quote_status":' in word:
                    del tweet[0]
                    timeline.append(tweet)
                    tweet = []
                    append = False    
                    
    # doesnt catch all of the values on the first run for some reason
    # takes a couple of loops of processign to get what we want
    l = 100 
    while l != 0:
        l = clean(timeline)

    
    id = row['_unit_id'].values[0]
    #print id

    sindex = 0
    if len(timeline) > 0:
        for state in stateids:
            if id in state.values:
                # write to file
                l_ = row['labels'].values[0]
                fname = state_filenames[sindex]
                write_timeline_country(timeline, fname, l_)

            sindex += 1

Wall time: 4min 43s

In [204]:

def write_timeline_country(timeline, filename, label):
    #fname = '../locations_manual/'+filename+'_extended.txt'
    
    with open(filename, 'a+') as f:
        f.write(label)
        
        numtweets = 0
        for tweet in timeline:
            for word in tweet:
                #print word
                f.write(word)
                f.write(' ')
            numtweets += 1
            if numtweets == 200:
                f.write('\n')
                f.write(label)
                numtweets = 0
                
            f.write('\t')

In [269]:
%%time

# get state dataset statistics

num_eachstate = [0] * len(stateids)
num_femalestate = [0] * len(stateids)
num_malestate = [0] * len(stateids)

print "number of states found ", len(stateids)

numactive = 0
len_eachtimeline = []

for filename in filenames:
    screenname = filename[18:-4]
    row = manset.loc[manset['name'] == screenname]
    
    with open(filename, "r") as tweets_file:
        timeline = []
        tweet = []
        for line in tweets_file:
            append = False
            for word in line.split():            
                if word == '"text":':
                    append = True

                if append == True and word != '"is_quote_status":':
                    tweet.append(word)

                if '"is_quote_status":' in word:
                    del tweet[0]
                    timeline.append(tweet)
                    tweet = []
                    append = False    
                    
    # doesnt catch all of the values on the first run for some reason
    # takes a couple of loops of processign to get what we want
    l = 100 
    while l != 0:
        l = clean(timeline)

    
    id = row['_unit_id'].values[0]
    l_ = row['gender'].values[0]
    #print id
    
    sindex = 0
    if len(timeline) > 200:
        for state in stateids:
            if id in state.values:
                num_eachstate[sindex] += 1
                
                if l_ == 'female':
                    num_femalestate[sindex] += 1
                elif l_ == 'male':
                    num_malestate[sindex] += 1
            sindex += 1

number of states found  51
Wall time: 4min 24s

In [270]:
num_eachstate
i = 0
for n in num_eachstate:
    if n > 0:
        i += 1
    
print i
print num_eachstate
print
print num_femalestate
print
print num_malestate

31
[3, 3, 2, 7, 7, 1, 2, 0, 2, 3, 1, 2, 0, 1, 1, 0, 3, 2, 1, 5, 1, 0, 2, 0, 2, 1, 1, 3, 1, 4, 6, 1, 0, 1, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[0, 0, 2, 2, 4, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 3, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[3, 3, 0, 5, 3, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0, 0, 2, 0, 4, 0, 0, 1, 0, 1, 1, 1, 2, 0, 2, 4, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [261]:
%%time

# get country dataset statistics

print "number of countries found ", len(countryids)

num_eachcountry = [0] * len(countryids)
num_femalescountry = [0] * len(countryids)
num_malescountry = [0] * len(countryids)

numactive = 0
len_eachtimeline = []

for filename in filenames:
    screenname = filename[18:-4]
    row = manset.loc[manset['name'] == screenname]
    
    with open(filename, "r") as tweets_file:
        timeline = []
        tweet = []
        for line in tweets_file:
            append = False
            for word in line.split():            
                if word == '"text":':
                    append = True

                if append == True and word != '"is_quote_status":':
                    tweet.append(word)

                if '"is_quote_status":' in word:
                    del tweet[0]
                    timeline.append(tweet)
                    tweet = []
                    append = False    
                    
    # doesnt catch all of the values on the first run for some reason
    # takes a couple of loops of processign to get what we want
    l = 100 
    while l != 0:
        l = clean(timeline)

    
    id = row['_unit_id'].values[0]
    l_ = row['gender'].values[0]
    #print l_

    
    cindex = 0
    if len(timeline) > 200:
        for c in countryids:
            if id in c.values:
                num_eachcountry[cindex] += 1
                
                if l_ == 'female':
                    num_femalescountry[cindex] += 1
                elif l_ == 'male':
                    num_malescountry[cindex] += 1
                    
            cindex += 1

number of countries found  50
Wall time: 4min 11s

In [266]:
print len(num_eachcountry)

i = 0
for n in num_eachcountry:
    if n > 0:
        i += 1
    
print i

print num_eachcountry
print
print num_femalescountry
print
print num_malescountry

50
24
[75, 4, 8, 3, 4, 1, 0, 0, 2, 7, 1, 11, 0, 0, 0, 0, 2, 1, 1, 0, 2, 3, 4, 0, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]

[31, 0, 4, 0, 2, 1, 0, 0, 1, 5, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

[44, 4, 4, 3, 2, 0, 0, 0, 1, 2, 0, 9, 0, 0, 0, 0, 2, 1, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]